services:
  mongo:
    image: mongo:6
    container_name: mongo_template
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network

  services_template:
    container_name: services_0
    build:
      context: .
      dockerfile: ./apps/services_template/Dockerfile
    environment:
      PORT: "3000"
      MONGO_URI: "mongodb://mongo:27017"    # use the mongo service name
      MONGO_DB_NAME: "user_db"
    depends_on:
      - mongo
    restart: always
    ports:
      - "3000:3000"                         # host:container
    volumes:
      - ./apps/services_template/logs:/apps/logs
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local