services:
  web:
    container_name: webs
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: runner
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app_network

  services_template:
    container_name: services_0
    build:
      context: .
      dockerfile: ./apps/services_template/Dockerfile
    environment:
      - PORT=3001
    restart: always
    ports:
      - "8001:3001"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    external: true
